import json
from dataclasses import dataclass
from pathlib import Path


@dataclass
class Enchantment:
    name: str
    namespace: str
    tier: int = 1
    max_level: int = 1

    def __init__(self, name: str, namespace: str, tier: int = 1, max_level: int = 1):
        self.name = name
        self.namespace = namespace
        self.tier = tier
        self.max_level = max_level

    def __hash__(self):
        return hash(tuple(self))


ENCHANTMENTS = [
    # disabled
    Enchantment("protection", "minecraft", 0, 0),
    Enchantment("sharpness", "minecraft", 0, 0),
    Enchantment("creeper_alloy", "enchantencore", 0, 0),
    Enchantment("crispbread", "enchantencore", 0, 0),
    Enchantment("hunger_aspect", "enchantencore", 0, 0),
    Enchantment("hunger_splash", "enchantencore", 0, 0),
    Enchantment("saturation_splash", "enchantencore", 0, 0),
    Enchantment("scholar_of_blocks", "enchantencore", 0, 0),
    Enchantment("scholar_of_mobs", "enchantencore", 0, 0),
    Enchantment("swift_slash", "enchantencore", 0, 0),
    Enchantment("mending", "minecraft", 0, 0),
    Enchantment("cleansing", "enchantencore", 0, 0),
    Enchantment("handyman", "enchantencore", 0, 0),
    Enchantment("illumination", "enchantencore", 0, 0),
    # Tier 1
    Enchantment("aqua_affinity", "minecraft", 1, 1),
    Enchantment("depth_strider", "minecraft", 1, 3),
    Enchantment("hell_strider", "netherdepthsupgrade", 1, 2),
    Enchantment("frost_walker", "minecraft", 1, 2),
    Enchantment("magma_walker", "enchantencore", 1, 2),
    Enchantment("lure", "minecraft", 1, 3),
    Enchantment("respiration", "minecraft", 1, 3),
    Enchantment("thorns", "minecraft", 1, 3),
    Enchantment("loyalty", "minecraft", 1, 3),
    Enchantment("catalysis", "deeperdarker", 1, 3),
    Enchantment("ocean_grace_enchant", "majospellenchantment", 1, 4),
    Enchantment("party_leader_enchant", "majospellenchantment", 1, 2),
    Enchantment("phase_dashed_enchant", "majospellenchantment", 1, 3),
    Enchantment("soulbound", "yigd", 1, 1),
    Enchantment("bunny_hop", "enchantencore", 1, 3),
    Enchantment("crab_claw", "enchantencore", 1, 3),
    Enchantment("crop_dance", "enchantencore", 1, 1),
    Enchantment("electric_walker", "enchantencore", 1, 1),
    Enchantment("end_speed", "enchantencore", 1, 3),
    Enchantment("glass_breaker", "enchantencore", 1, 1),
    Enchantment("gluttony", "enchantencore", 1, 5),
    Enchantment("grass_walker", "enchantencore", 1, 2),
    Enchantment("growth", "enchantencore", 1, 5),
    Enchantment("shrinkage", "enchantencore", 1, 5),
    Enchantment("night_vision", "enchantencore", 1, 1),
    Enchantment("pickpocket", "enchantencore", 1, 1),
    Enchantment("pufferfish", "enchantencore", 1, 1),
    Enchantment("sand_speed", "enchantencore", 1, 3),
    Enchantment("seeker", "enchantencore", 1, 3),
    Enchantment("summer_walker", "enchantencore", 1, 2),
    Enchantment("cherry_leaves_arrow_trail", "enchantencore", 1, 1),
    Enchantment("cherry_leaves_trail", "enchantencore", 1, 1),
    Enchantment("cosy_smoke_arrow_trail", "enchantencore", 1, 1),
    Enchantment("cosy_smoke_trail", "enchantencore", 1, 1),
    Enchantment("dolphin_arrow_trail", "enchantencore", 1, 1),
    Enchantment("dolphin_trail", "enchantencore", 1, 1),
    Enchantment("dripping_honey_arrow_trail", "enchantencore", 1, 1),
    Enchantment("dripping_honey_trail", "enchantencore", 1, 1),
    Enchantment("dripping_lava_arrow_trail", "enchantencore", 1, 1),
    Enchantment("dripping_lava_trail", "enchantencore", 1, 1),
    Enchantment("dripping_obsidian_tear_arrow_trail", "enchantencore", 1, 1),
    Enchantment("dripping_obsidian_tear_trail", "enchantencore", 1, 1),
    Enchantment("dripping_water_arrow_trail", "enchantencore", 1, 1),
    Enchantment("dripping_water_trail", "enchantencore", 1, 1),
    Enchantment("enchant_arrow_trail", "enchantencore", 1, 1),
    Enchantment("enchant_trail", "enchantencore", 1, 1),
    Enchantment("end_rod_arrow_trail", "enchantencore", 1, 1),
    Enchantment("end_rod_trail", "enchantencore", 1, 1),
    Enchantment("firework_arrow_trail", "enchantencore", 1, 1),
    Enchantment("firework_trail", "enchantencore", 1, 1),
    Enchantment("flame_arrow_trail", "enchantencore", 1, 1),
    Enchantment("flame_trail", "enchantencore", 1, 1),
    Enchantment("happy_villager_arrow_trail", "enchantencore", 1, 1),
    Enchantment("happy_villager_trail", "enchantencore", 1, 1),
    Enchantment("heart_arrow_trail", "enchantencore", 1, 1),
    Enchantment("heart_trail", "enchantencore", 1, 1),
    Enchantment("note_arrow_trail", "enchantencore", 1, 1),
    Enchantment("note_trail", "enchantencore", 1, 1),
    Enchantment("ominous_spawning_arrow_trail", "enchantencore", 1, 1),
    Enchantment("ominous_spawning_trail", "enchantencore", 1, 1),
    Enchantment("portal_arrow_trail", "enchantencore", 1, 1),
    Enchantment("portal_trail", "enchantencore", 1, 1),
    Enchantment("raid_omen_arrow_trail", "enchantencore", 1, 1),
    Enchantment("raid_omen_trail", "enchantencore", 1, 1),
    Enchantment("scrape_arrow_trail", "enchantencore", 1, 1),
    Enchantment("scrape_trail", "enchantencore", 1, 1),
    Enchantment("sculk_soul_arrow_trail", "enchantencore", 1, 1),
    Enchantment("sculk_soul_trail", "enchantencore", 1, 1),
    Enchantment("snowflake_arrow_trail", "enchantencore", 1, 1),
    Enchantment("snowflake_trail", "enchantencore", 1, 1),
    Enchantment("soul_fire_flame_arrow_trail", "enchantencore", 1, 1),
    Enchantment("soul_fire_flame_trail", "enchantencore", 1, 1),
    Enchantment("totem_arrow_trail", "enchantencore", 1, 1),
    Enchantment("totem_trail", "enchantencore", 1, 1),
    Enchantment("trial_omen_arrow_trail", "enchantencore", 1, 1),
    Enchantment("trial_omen_trail", "enchantencore", 1, 1),
    Enchantment("wax_off_arrow_trail", "enchantencore", 1, 1),
    Enchantment("wax_off_trail", "enchantencore", 1, 1),
    Enchantment("wax_on_arrow_trail", "enchantencore", 1, 1),
    Enchantment("wax_on_trail", "enchantencore", 1, 1),
    Enchantment("witch_arrow_trail", "enchantencore", 1, 1),
    Enchantment("witch_trail", "enchantencore", 1, 1),
    Enchantment("acrobat", "combat_roll", 1, 5),
    Enchantment("longfooted", "combat_roll", 1, 4),
    Enchantment("multi_roll", "combat_roll", 1, 3),
    # Tier 2
    Enchantment("feather_falling", "minecraft", 2, 4),
    Enchantment("efficiency", "minecraft", 2, 5),
    Enchantment("knockback", "minecraft", 2, 2),
    Enchantment("luck_of_the_sea", "minecraft", 2, 3),
    Enchantment("mending", "minecraft", 2, 1),
    Enchantment("swift_sneak", "minecraft", 2, 3),
    Enchantment("unbreaking", "minecraft", 2, 3),
    Enchantment("blast_protection", "minecraft", 2, 4),
    Enchantment("projectile_protection", "minecraft", 2, 4),
    Enchantment("fire_protection", "minecraft", 2, 4),
    Enchantment("multishot", "minecraft", 2, 1),
    Enchantment("punch", "minecraft", 2, 2),
    Enchantment("blood_mana_enchant", "majospellenchantment", 2, 3),
    Enchantment("gentle_graveyard_keeper_enchant", "majospellenchantment", 2, 3),
    Enchantment("hopeless_power_enchant", "majospellenchantment", 2, 3),
    Enchantment("max_mana_enchant", "majospellenchantment", 2, 5),
    Enchantment("stasis", "supplementaries", 2, 1),
    Enchantment("clearing_strike", "vein_vantage", 2, 2),
    Enchantment("ore_blessing", "vein_vantage", 2, 3),
    Enchantment("vein_sweep", "vein_vantage", 2, 8),
    Enchantment("bulletproof", "enchantencore", 2, 1),
    Enchantment("darkness_alloy", "enchantencore", 2, 3),
    Enchantment("ender_shot", "enchantencore", 2, 1),
    Enchantment("enderscape", "enchantencore", 2, 1),
    Enchantment("invisibility_cloak", "enchantencore", 2, 1),
    Enchantment("midas_touch", "enchantencore", 2, 1),
    Enchantment("moonwalk", "enchantencore", 2, 3),
    Enchantment("pegasus", "enchantencore", 2, 1),
    Enchantment("poppy_peace", "enchantencore", 2, 1),
    Enchantment("rabbit_foot", "enchantencore", 2, 5),
    Enchantment("rejuvenation", "enchantencore", 2, 5),
    Enchantment("safe_landing", "enchantencore", 2, 5),
    Enchantment("sonic", "enchantencore", 2, 3),
    Enchantment("sting", "enchantencore", 2, 1),
    Enchantment("switch", "enchantencore", 2, 1),
    # Tier 3
    Enchantment("bane_of_arthropods", "minecraft", 3, 5),
    Enchantment("smite", "minecraft", 3, 5),
    Enchantment("impaling", "minecraft", 3, 5),
    Enchantment("sculk_smite", "deeperdarker", 3, 5),
    Enchantment("bane_of_bosses", "enchantencore", 3, 5),
    Enchantment("bane_of_netherborn", "enchantencore", 3, 5),
    Enchantment("bane_of_raiders", "enchantencore", 3, 5),
    Enchantment("phantom_menace", "enchantencore", 3, 5),
    Enchantment("fire_aspect", "minecraft", 3, 2),
    Enchantment("flame", "minecraft", 3, 1),
    Enchantment("soul_speed", "minecraft", 3, 3),
    Enchantment("breach", "minecraft", 3, 4),
    Enchantment("piercing", "minecraft", 3, 4),
    Enchantment("quick_charge", "minecraft", 3, 3),
    Enchantment("daylight_anthem_enchant", "majospellenchantment", 3, 3),
    Enchantment("nocturne_aria_enchant", "majospellenchantment", 3, 3),
    Enchantment("excitatio_arcana_enchant", "majospellenchantment", 3, 3),
    Enchantment("necrovolt_enchant", "majospellenchantment", 3, 3),
    Enchantment("ice_fire_song_enchant", "majospellenchantment", 3, 3),
    Enchantment("nether_heart_enchant", "majospellenchantment", 3, 3),
    Enchantment("firepower", "simplemusket", 3, 5),
    Enchantment("longshot", "simplemusket", 3, 2),
    Enchantment("marking", "usefulspyglass", 3, 1),
    Enchantment("precision", "usefulspyglass", 3, 1),
    Enchantment("spotter", "usefulspyglass", 3, 1),
    Enchantment("fire_alloy", "enchantencore", 3, 3),
    Enchantment("ice_alloy", "enchantencore", 3, 3),
    Enchantment("pacifier", "enchantencore", 3, 3),
    Enchantment("red_moon", "enchantencore", 3, 3),
    Enchantment("sea_breeze", "enchantencore", 3, 3),
    # Tier 4
    Enchantment("fortune", "minecraft", 4, 3),
    Enchantment("looting", "minecraft", 4, 3),
    Enchantment("power", "minecraft", 4, 5),
    Enchantment("density", "minecraft", 4, 5),
    Enchantment("silk_touch", "minecraft", 4, 1),
    Enchantment("sweeping_edge", "minecraft", 4, 3),
    Enchantment("channeling", "minecraft", 4, 1),
    Enchantment("riptide", "minecraft", 4, 3),
    Enchantment("wind_burst", "minecraft", 4, 3),
    Enchantment("backstabbing", "farmersdelight", 4, 3),
    Enchantment("lunge", "mounts_of_mayhem", 4, 3),
    Enchantment("cd_reduction_enchant", "majospellenchantment", 4, 5),
    Enchantment("mana_mending_enchant", "majospellenchantment", 4, 1),
    Enchantment("mana_reaper_enchant", "majospellenchantment", 4, 5),
    Enchantment("red_lotus_enchant", "majospellenchantment", 4, 3),
    Enchantment("vlad_tepes_enchant", "majospellenchantment", 4, 4),
    Enchantment("spell_streak_enchant", "majospellenchantment", 4, 5),
    Enchantment("repeating", "simplemusket", 4, 1),
    Enchantment("boltbringer", "enchantencore", 4, 1),
    Enchantment("bomber", "enchantencore", 4, 2),
    Enchantment("hardened", "enchantencore", 4, 5),
    Enchantment("haste", "enchantencore", 4, 3),
    Enchantment("infested_aspect", "enchantencore", 4, 2),
    Enchantment("levitation_aspect", "enchantencore", 4, 2),
    Enchantment("leech", "enchantencore", 4, 1),
    Enchantment("lightning_bolt", "enchantencore", 4, 1),
    Enchantment("ominous_healing", "enchantencore", 4, 1),
    Enchantment("oozing_aspect", "enchantencore", 4, 2),
    Enchantment("poison_aspect", "enchantencore", 4, 2),
    Enchantment("replenish", "enchantencore", 4, 1),
    Enchantment("sacrifice", "enchantencore", 4, 5),
    Enchantment("slowness_aspect", "enchantencore", 4, 2),
    Enchantment("weakness_aspect", "enchantencore", 4, 2),
    Enchantment("weaving_aspect", "enchantencore", 4, 2),
    Enchantment("wind_aspect", "enchantencore", 4, 2),
    Enchantment("wither_aspect", "enchantencore", 4, 2),
    # Tier 5
    Enchantment("infinity", "minecraft", 5, 1),
    Enchantment("bedrocker", "enchantencore", 5, 1),
    Enchantment("blindness_splash", "enchantencore", 5, 1),
    Enchantment("day_protection", "enchantencore", 5, 4),
    Enchantment("end_protection", "enchantencore", 5, 4),
    Enchantment("nether_protection", "enchantencore", 5, 4),
    Enchantment("night_protection", "enchantencore", 5, 4),
    Enchantment("evokers_wrath", "enchantencore", 5, 1),
    Enchantment("flare", "enchantencore", 5, 5),
    Enchantment("forge_shot", "enchantencore", 5, 1),
    Enchantment("glowing_splash", "enchantencore", 5, 1),
    Enchantment("invisibility_splash", "enchantencore", 5, 1),
    Enchantment("levitation_splash", "enchantencore", 5, 1),
    Enchantment("ominous_rain", "enchantencore", 5, 1),
    Enchantment("poison_splash", "enchantencore", 5, 1),
    Enchantment("regeneration_splash", "enchantencore", 5, 1),
    Enchantment("shulker_shell", "enchantencore", 5, 1),
    Enchantment("slowness_splash", "enchantencore", 5, 1),
    Enchantment("weakness_splash", "enchantencore", 5, 1),
    Enchantment("wither_splash", "enchantencore", 5, 1),
    Enchantment("dominion_helm_enchant", "majospellenchantment", 5, 3),
]

TIERS = {
    0: "",
    1: "irons_spellbooks:common_ink",
    2: "irons_spellbooks:uncommon_ink",
    3: "irons_spellbooks:rare_ink",
    4: "irons_spellbooks:epic_ink",
    5: "irons_spellbooks:legendary_ink",
}

if __name__ == "__main__":
    for ench in ENCHANTMENTS:
        print(f"Filename: {ench.namespace}/{ench.name}")
        # Tier 0 are disabled enchantments
        if ench.tier == 0:
            ench_dict = {}
        else:
            ench_dict = {"levels": {}}

            for i in range(ench.max_level):
                ench_dict["levels"][i + 1] = {
                    "item": TIERS[ench.tier],
                    "amount": 2**i,
                }
        Path(
            f"datapacks/phis_immersive_enchanting/data/immersiveenchanting/enchantment_costs/{ench.namespace}"
        ).mkdir(parents=True, exist_ok=True)
        with open(
            f"datapacks/phis_immersive_enchanting/data/immersiveenchanting/enchantment_costs/{ench.namespace}/{ench.name}.json",
            "w",
        ) as f:
            f.write(json.dumps(ench_dict, indent=2))
