LootJS.lootTables((event) => {
  const chests = [
    "abandoned_mineshaft",
    "bastion_bridge",
    "igloo_chest",
    "pillager_outpost",
    "shipwreck_treasure",
    "simple_dungeon",
    "stronghold_corridor",
    "village/village_desert_house",
    "village/village_plains_house",
    "village/village_savanna_house",
    "village/village_snowy_house",
    "village/village_taiga_house",
    "woodland_mansion",
  ];

  for (const chest of chests) {
    event.getLootTable(`minecraft:chests/${chest}`).createPool((pool) => {
      pool
        .rolls([0, 1])
        .addEntry(LootEntry.of("plushie_buddies:plushie_allay"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_axolotl"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_bee"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_chicken"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_cow"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_fox"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_parrot"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_pig"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_sheep"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_turtle"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_camel"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_cat"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_creeper"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_dolphin"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_enderdragon"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_enderman"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_frog"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_ghast"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_goat"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_horse"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_mooshroom"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_panda"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_polar_bear"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_pufferfish"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_rabbit"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_skeleton_horse"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_sniffer"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_squid"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_wolf"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_donkey"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_bat"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_phantom"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_skeleton"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_spider"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_warden"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_witch"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_wither"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_wither_skeleton"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_zoglin"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_zombie"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_trader_lama"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_villager"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_wandering_trader"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_zombie_villager"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_iron_golem"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_evoker"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_pillager"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_ravanger"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_vex"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_vindicator"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_blaze"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_drowned"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_hoglin"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_husk"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_magma_cube"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_piglin"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_piglin_brute"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_stray"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_strider"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_zombified_piglin"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_armadillo"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_breeze"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_cave_spider"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_glow_squid"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_guardian"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_llama"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_mule"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_shulker"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_slime"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_elder_guardian"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_peter"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_dark_father"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_emperor"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_yoga"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_chewie"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_dan_rolo"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_storm_soldier"))
        .when((condition) => {
          condition.randomChance(0.1);
        });
    });
  }

  const baby_mobs = ["zombie"];

  for (const mob of baby_mobs) {
    event.getLootTable(`minecraft:entities/${mob}`).createPool((pool) => {
      pool
        .rolls([0, 1])
        .addEntry(LootEntry.of("plushie_buddies:plushie_allay"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_axolotl"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_bee"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_chicken"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_cow"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_fox"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_parrot"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_pig"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_sheep"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_turtle"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_camel"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_cat"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_creeper"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_dolphin"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_enderdragon"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_enderman"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_frog"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_ghast"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_goat"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_horse"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_mooshroom"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_panda"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_polar_bear"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_pufferfish"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_rabbit"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_skeleton_horse"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_sniffer"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_squid"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_wolf"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_donkey"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_bat"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_phantom"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_skeleton"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_spider"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_warden"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_witch"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_wither"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_wither_skeleton"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_zoglin"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_zombie"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_trader_lama"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_villager"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_wandering_trader"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_zombie_villager"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_iron_golem"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_evoker"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_pillager"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_ravanger"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_vex"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_vindicator"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_blaze"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_drowned"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_hoglin"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_husk"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_magma_cube"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_piglin"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_piglin_brute"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_stray"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_strider"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_zombified_piglin"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_armadillo"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_breeze"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_cave_spider"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_glow_squid"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_guardian"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_llama"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_mule"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_shulker"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_slime"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_elder_guardian"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_peter"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_dark_father"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_emperor"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_yoga"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_chewie"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_dan_rolo"))
        .addEntry(LootEntry.of("plushie_buddies:plushie_storm_soldier"))
        .when((condition) => {
          condition.randomChance(0.02) &&
            condition.killedByPlayer() &&
            condition.matchEntityCustom((entity) => {
              return entity.baby;
            });
        });
    });
  }
});
