StartupEvents.registry('item', event => {
  event.create('infinity_key')
   .displayName('Infinity Key')
   .texture('phis:item/infinity_key')
   .rarity('rare')
   .fireResistant(true)
   .tooltip("Can be charged by using it on ���� in the End dimension.")
  
  event.create('infinity_key_charged')
   .displayName('Charged Infinity Key')
   .texture('phis:item/infinity_key_charged')
   .rarity('epic')
   .fireResistant(true)
   .unstackable()
   .glow(true)
   .tooltip("§d§kPowered by Liquid Null!§r")
})