#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue Nov 18 19:50:08 GMT 2025
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=Yamashita Shimejize v1.3.zip
