#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Jan 18 01:17:51 CET 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=superDuperVanilla.zip
