#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Jan 23 21:49:32 CET 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=superDuperVanilla.zip
