version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "CHECK"
leavesCullingAmount = 2
includeMangroveRoots = false
endGatewayCulling = false
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
fastitemframes = true
luminous_beasts = true
farmersdelight = true
rubinated_nether = true
moresnifferflowers = true
hoppergadgetry = true
chimes = true
friendsandfoes = true
irons_spellbooks = true
comforts = true
simpletms = true
sootychimneys = true
yigd = true
spring_to_life = true
fastpaintings = true
arcaneessenceblock = true
sweety_garden = true
amendments = true
handcrafted = true
mynethersdelight = true
advancementframes = true
vanillabackport = true
snowrealmagic = true
cobblemon = true
biomesoplenty = true
linkedchests = true
netherchested = true
exposure = true
gardens_of_the_dead = true
new_slab_variants = true
infinity = true
endersdelight = true
supplementaries = true
chipped = true
suppsquared = true
deeperdarker = true
endrem = true
copperagebackport = true
itsalive = true
echochest = true
minecraft = true
alshanex_familiars = true
lootr = true
bosses_of_mass_destruction = true
astages = true
endermanoverhaul = true
randomore = true
waystones = true
creeperoverhaul = true
monolib = true
ditr = true
rocks = true
realmrpg_skeletons = true
immersiveenchanting = true
crittersandcompanions = true
netherdepthsupgrade = true
