[general]
	#List of waystone origins that should prevent others from editing. PLAYER is special in that it allows only edits by the owner of the waystone.
	restrictedWaystones = ["PLAYER"]
	#Set to "GLOBAL" to have newly placed or found waystones be global by default.
	#Allowed Values: ACTIVATION, GLOBAL, SHARD_ONLY, ORANGE_SHARESTONE, MAGENTA_SHARESTONE, LIGHT_BLUE_SHARESTONE, YELLOW_SHARESTONE, LIME_SHARESTONE, PINK_SHARESTONE, GRAY_SHARESTONE, LIGHT_GRAY_SHARESTONE, CYAN_SHARESTONE, PURPLE_SHARESTONE, BLUE_SHARESTONE, BROWN_SHARESTONE, GREEN_SHARESTONE, RED_SHARESTONE, BLACK_SHARESTONE
	defaultVisibility = "ACTIVATION"
	#Add "GLOBAL" to allow every player to create global waystones.
	allowedVisibilities = []
	#The time in ticks that it takes to use a warp stone. This is the charge-up time when holding right-click.
	warpStoneUseTime = 32
	#The time in ticks that it takes to use a warp plate. This is the time the player has to stand on top for.
	warpPlateUseTime = 15
	#The time in ticks it takes to use a scroll. This is the charge-up time when holding right-click.
	scrollUseTime = 32

[inventoryButton]
	#Set to 'NONE' for no inventory button. Set to 'NEAREST' for an inventory button that teleports to the nearest waystone. Set to 'ANY' for an inventory button that opens the waystone selection menu. Set to a waystone name for an inventory button that teleports to a specifically named waystone.
	inventoryButton = ""
	#The x position of the inventory button in the inventory.
	inventoryButtonX = 58
	#The y position of the inventory button in the inventory.
	inventoryButtonY = 60
	#The y position of the inventory button in the creative menu.
	creativeInventoryButtonX = 88
	#The y position of the inventory button in the creative menu.
	creativeInventoryButtonY = 33

[worldGen]
	#Set to 'DEFAULT' to only generate the normally textured waystones. Set to 'MOSSY' or 'SANDY' to generate all as that variant. Set to 'BIOME' to make the style depend on the biome it is generated in.
	#Allowed Values: DEFAULT, MOSSY, SANDY, BLACKSTONE, DEEPSLATE, END_STONE, BIOME
	wildWaystoneStyle = "BIOME"
	#Approximate chunk distance between wild waystones being generated. Set to 0 to disable generation.
	chunksBetweenWildWaystones = 0
	#List of dimensions that wild waystones are allowed to spawn in. If left empty, all dimensions except those in wildWaystonesDimensionDenyList are used.
	wildWaystonesDimensionAllowList = ["minecraft:the_end", "minecraft:overworld", "minecraft:the_nether"]
	#List of dimensions that wild waystones are not allowed to spawn in. Only used if wildWaystonesDimensionAllowList is empty.
	wildWaystonesDimensionDenyList = []
	#Set to 'PRESET_FIRST' to first use names from the nameGenerationPresets. Set to 'PRESET_ONLY' to use only those custom names. Set to 'MIXED' to have some waystones use custom names, and others random names.
	#Allowed Values: PRESET_FIRST, RANDOM_ONLY, PRESET_ONLY, MIXED
	nameGenerationMode = "PRESET_FIRST"
	#The template to use when generating new names. Supported placeholders are {Biome} (english biome name) and {MrPork} (the default name generator).
	nameGenerationTemplate = "{MrPork}"
	#These names will be used for the PRESET name generation mode. See the nameGenerationMode option for more info.
	nameGenerationPresets = [
		"Ahghairon's Tower",
		"Akhlaur's Tower",
		"Alathir Spire",
		"Amber Ledge",
		"Andromath's Rise",
		"Anguish Point",
		"Anthormbrur",
		"Aquas and Azures",
		"Arcane Tower",
		"Archmage Overwatch",
		"Askalath's Tower",
		"Auret",
		"Baharrokhbrur",
		"Basalt Tower",
		"Beacon Tower",
		"Beacon of Tyrhold",
		"Beastwatch Tower",
		"Beckoning Tower of Shoon",
		"Beggar's Haunt",
		"Belfry of Lament",
		"Bell Tower of Waterdeep",
		"Bell Tower",
		"Bellcrest Spire",
		"Black Helm Tower",
		"Blackgorgons",
		"Blackhawk's Bulwark",
		"Blackhorn's Penance",
		"Blackstaff Tower",
		"Bleeding Ziggurat",
		"Blood Island",
		"Bloodarch Gate",
		"Bone Chipper",
		"Boonmoppet's Tower",
		"Boulder Tower",
		"Brimstone Tower",
		"Brute's Rise",
		"Caddelyn's Tower",
		"Campanar",
		"Cholandrothipe's Tower",
		"Citadel of Conjurers",
		"Cliffhorn Watch",
		"Cloak Tower",
		"Cloquièr",
		"Clouded Keep",
		"Cloudtop Tower",
		"Clymph Tower",
		"Cold Tower",
		"Constable's Tower",
		"Cordana's Apex",
		"Cormyr Border Outpost",
		"Corondor's Tower",
		"Corwell's Steeple",
		"Crescent Grove",
		"Crestfall Rise",
		"Crown Guard Tower",
		"Crusader's Outpost",
		"Crusaders' Pinnacle",
		"Crystal Spire",
		"Damien's Tower",
		"Darkfollow's Spire",
		"Darkwall Tower",
		"Darnarest's Tower",
		"Darstil's Tower",
		"Dawn Tower",
		"Dawnstar Spire",
		"Death Tower",
		"Deathforge Tower",
		"Delfen's Tower",
		"Demonstone",
		"Denlor's Tower",
		"Dhoelath's Tower",
		"Disruptor Tower",
		"Domination Point Tower",
		"Doom Tower",
		"Dragon Tower",
		"Dragonspear",
		"Drum Tower",
		"Duraludon",
		"Durlag's Tower",
		"Duskwither Spire",
		"Earth-Fury Tower",
		"East Frostwolf Tower",
		"East Sanctum",
		"East Spire",
		"East Torch Tower",
		"Eastpoint Tower",
		"Eastwall Tower",
		"Elaph's Tower",
		"Elevated Temple",
		"Elminster's Tower",
		"Ember Spear Tower",
		"Emberfall Tower",
		"Emberfall Watch",
		"Emerald Spire",
		"Endcliff Tower",
		"Energy Tower",
		"Ethel Rethor",
		"Evermoon Terrace",
		"Everwatch",
		"Farwatch Tower",
		"Feathergale Spire",
		"Fingers of Szass Tam",
		"Firefinger",
		"Firefinger's Tower",
		"Flame Tower",
		"Flamewatch Tower",
		"Flaming Tower",
		"Flamsterd Tower",
		"Floating Tower",
		"Forgotten Keep",
		"Frosthoof Watch",
		"Fyrtårn",
		"Fzoul's Tower",
		"Gallows' Corner",
		"Gaol Tower",
		"Gate of Revelations",
		"Gaze of the Legion",
		"Gormaul Tower",
		"Grainhouse",
		"Grand Gate of Delights",
		"Grand Steeple",
		"Granite Tower",
		"Great Keep",
		"Great Spire of the Ice Sea",
		"Greenwarden's Grove",
		"Guard Tower of the City of the Dead",
		"Halaster's Hold",
		"Hall of Winds",
		"Harbortower",
		"Harborwatch Tower",
		"Haunted Precipice",
		"Hawk's Nest",
		"High Tower of Iriaebor",
		"High Tower of Thalivar",
		"Host Tower of the Arcane",
		"Howling Ziggurat",
		"Hunter's Rise",
		"Iceblood Tower",
		"Imryth Tower",
		"Iniarv's Tower",
		"Inverted Tower",
		"Iron Throne",
		"Iron Tower",
		"Ivory Tower",
		"Jacob's Ladder",
		"Kaknästornet",
		"Kepetur",
		"Khadgar's Tower",
		"Kurth Tower",
		"Kyrkklocka",
		"Ladysluck Tower",
		"Largo's Overlook",
		"Lehrengate",
		"Light's Point",
		"Light's Shield",
		"Lightning Spire",
		"Lion Tower",
		"Lion's Landing",
		"Lion's Redoubt",
		"Liongirt Tower",
		"Lonely Citadel",
		"Lonely Tower",
		"Lost Point",
		"Luskan Sea Tower",
		"Maestra's Post",
		"Mage's Tower",
		"Magis Tor",
		"Maligor's Tower",
		"Malkith's Tower",
		"Malthuk's Tower",
		"Many-Windowed Tower",
		"Maskyr's Tower",
		"Memory Spire",
		"Mhair's Tower",
		"Monolith Shard",
		"Monument of the Achievements of the Enlightened Throne",
		"Monument of the Arch-Illager",
		"Moongleam Tower",
		"Moonlit Tower",
		"Moonrise Towers",
		"Moonspire",
		"Mor'dul Tower",
		"Mor'shan Rampart",
		"Morhion's Tower",
		"Mortwake's Tower",
		"Mrelgaunt's Turret",
		"Naingate",
		"Narthtowers",
		"Nashal the Watcher",
		"Nath'raxas Spire",
		"Nebula Pillar",
		"Nerubian Ziggurat",
		"Nezram's Tower",
		"Nightwatcher's Perch",
		"Nine Sentinels",
		"North Sanctum",
		"North Spear",
		"North Tower",
		"Northend Tower",
		"Northmaul Tower",
		"Northpass Tower",
		"Northwind Keep",
		"Onslaught Base Camp",
		"Onyx Tower",
		"Orosul's Tower",
		"Overlook",
		"Palace of Loss",
		"Phoenix Tower",
		"Pillar of Ash",
		"Pillar of Creation",
		"Plaguewood Tower",
		"Plinth",
		"Pristal Towers",
		"Qysaghanni Fortress",
		"Ramazith's Tower",
		"Ranger's Foothold",
		"Raumkreml",
		"Raynewood Tower",
		"Razor Hill Watchtower",
		"Red Tower of Dayya",
		"Redelav Tower",
		"Revel's End",
		"Ridgepoint Tower",
		"Rimlost",
		"Ring of Blue Fire",
		"Rose-Crowned Tower",
		"Sanctum of the Moon",
		"Sanctum of the Stars",
		"Sanctum of the Sun",
		"Scarlet Tower",
		"Scarlet Watchtower",
		"Seaeyes Tower",
		"Seat of the Aspects",
		"Seatower of Balduran",
		"Seawatch Tower",
		"Sentinel Tower",
		"Sentry Point",
		"Sepulcher of Knowledge",
		"Serpent's Spine",
		"Seshrentor",
		"Sethrak Spire",
		"Sewer Keep",
		"Shadow Tower",
		"Shadowfang Tower",
		"Shadowsight Tower",
		"Sharburg",
		"Shatter Point",
		"Shattered Tower",
		"Shield Tower",
		"Shipsgrave Tower",
		"Silverhand Tower",
		"Skullspire",
		"Sky-Fury Tower",
		"Skyclave",
		"Skytower",
		"Slag Watch",
		"Sludgeguard Tower",
		"Sniffer's Outpost",
		"Solar Pillar",
		"South Spire",
		"Southmaul Tower",
		"Southpoint Tower",
		"Spearpoint Tower",
		"Spike",
		"Spire of Arak",
		"Spire of Blood",
		"Spire of Decay",
		"Spire of Pain",
		"Spire of Woe",
		"Spire of the Guardian",
		"Spire of the Unseen Guests",
		"Spires of Saerrentaun",
		"Spirit Tower",
		"Splinterspear Junction",
		"Staghelm Point",
		"Star Lookout",
		"Stardust Pillar",
		"Stardust Spire",
		"Starfall Turret",
		"Starmeadow Tower",
		"Starstalker's Point",
		"Starwatch Tower",
		"Stonehoof Watch",
		"Stonewatch Tower",
		"Storm Tower",
		"Stormkeep",
		"Stormweather Towers",
		"Sumcha's Tower",
		"Summer's Tower",
		"Sun's Reach Sanctum",
		"Sundamar's Tower",
		"Sundaroon's Seatower",
		"Sunreaver's Command",
		"Sunrise Tower",
		"Sunspire",
		"Suppression Spire",
		"Suzail Harbor Tower",
		"Syndra Wands' Tower",
		"Taelan's Tower",
		"Tarntassa's Tower",
		"Telkoun's Tower",
		"Tempest's Fury",
		"Temple of the Harvest Moon",
		"Tessalar's Tower",
		"Tessaril's Tower",
		"The Grand Outlook",
		"The Monolith",
		"The Obelisk",
		"The Observatory",
		"The One amidst the Skies",
		"The Roving Rune",
		"Three Torn Towers",
		"Throat",
		"Toranj",
		"Tower Arcanatorus",
		"Tower High",
		"Tower Higher than Eastpeak",
		"Tower Point",
		"Tower Reilloch",
		"Tower Threespires",
		"Tower Tor",
		"Tower Tranquil",
		"Tower Watch",
		"Tower of Adnan al-Raqi",
		"Tower of Al-Kalb",
		"Tower of Althalaxx",
		"Tower of Anhur",
		"Tower of Arathor",
		"Tower of Arcane Might",
		"Tower of Argûl",
		"Tower of Azora",
		"Tower of Balance",
		"Tower of Blessed Strength",
		"Tower of Bones",
		"Tower of Celadaine",
		"Tower of Congregation",
		"Tower of Dracandros",
		"Tower of Eldara",
		"Tower of Estulan",
		"Tower of Flames",
		"Tower of Harmony",
		"Tower of Ilgalar",
		"Tower of Life",
		"Tower of Martyrs",
		"Tower of Mourning",
		"Tower of Nephthys",
		"Tower of Osiris",
		"Tower of Pain Exalted",
		"Tower of Pizentios",
		"Tower of Pronouncement",
		"Tower of Riches",
		"Tower of Ruin",
		"Tower of Solace",
		"Tower of Stars",
		"Tower of Storms",
		"Tower of Twilight",
		"Tower of War",
		"Tower of Zephyros",
		"Tower of the Art",
		"Tower of the Damned",
		"Tower of the Dawn",
		"Tower of the Faceless God",
		"Tower of the Hamarch",
		"Tower of the High Wizard Netheril",
		"Tower of the Ice Witch",
		"Tower of the Lord Protector",
		"Tower of the Moon",
		"Tower of the Morning",
		"Tower of the Order",
		"Tower of the Rising Moon",
		"Tower of the Sun",
		"Tower of the Test",
		"Towers of Horus-Re",
		"Towers of Smoke",
		"Towers of Thoth",
		"Twilight Citadel",
		"Twin Towers of the Eternal Eclipse",
		"Twisted Tower of Ashaba",
		"Tårn",
		"Upper Towers",
		"Valdisdall",
		"Violet Citadel",
		"Violet Spire",
		"Violet Tower",
		"Vorpal Tower",
		"Vortex Pillar",
		"Wailing Ziggurat",
		"Walking Tower of Warglend",
		"Warden Towers",
		"Wardrobe of Jhaladass",
		"Warsong Lookout",
		"Watcher's Keep",
		"Watchkeep",
		"Watchman's Rise",
		"Watchman's Tower",
		"Watchway Tower",
		"Wave Tower",
		"West Frostwolf Tower",
		"West Point Tower",
		"West Sanctum",
		"West Spear Tower",
		"West Spire",
		"Westlight",
		"Whisperwind's Citadel",
		"White Agate's Tower",
		"Windrunner Spire",
		"Windrunner's Overlook",
		"Windsong Tower",
		"Winter's Edge Tower",
		"Wintergrasp Keep",
		"Wither's Nest",
		"Wizard's Sanctum",
		"Wyllow's Tower",
		"Wyrm Tower",
		"Wyvernwatch Castle",
		"Xonthal's Tower",
		"Xxiphu",
		"Xylem's Tower",
		"Yintras' Tower",
]
	#Set to REGULAR to have waystones spawn in some villages. Set to FREQUENT to have waystones spawn in most villages. Set to DISABLED to disable waystone generation in villages. Waystones will only spawn in vanilla or supported villages.
	#Allowed Values: DISABLED, REGULAR, FREQUENT
	spawnInVillages = "DISABLED"

[teleports]
	#Set to false to simply disable all xp costs. See warpRequirements for more fine-grained control.
	enableCosts = true
	#Set to false to simply disable all cooldowns. See warpRequirements for more fine-grained control.
	enableCooldowns = true
	#List of warp requirements with comma-separated parameters in parentheses. Conditions can be defined as comma-separated list in square brackets. Will be applied in order.
	warpRequirements = ["[source_is_warp_stone] add_cooldown(my_cooldown, 300)"]
	#Set to ENABLED to have nearby pets teleport with you. Set to SAME_DIMENSION to have nearby pets teleport with you only if you're not changing dimensions. Set to DISABLED to disable.
	#Allowed Values: ENABLED, SAME_DIMENSION, DISABLED
	transportPets = "DISABLED"
	#Set to ENABLED to have leashed mobs teleport with you. Set to SAME_DIMENSION to have leashed mobs teleport with you only if you're not changing dimensions. Set to DISABLED to disable.
	#Allowed Values: ENABLED, SAME_DIMENSION, DISABLED
	transportLeashed = "ENABLED"
	#List of entities that cannot be teleported, either as pet, leashed, or on warp plates.
	entityDenyList = ["minecraft:wither"]
	#Set to true to enable warp modifier items for applying status effects on teleports.
	enableModifiers = true

[client]
	#If enabled, the text overlay on waystones will no longer always render at full brightness.
	disableTextGlow = false

[compatibility]
	#If enabled, JourneyMap waypoints will be created for each activated waystone.
	journeyMap = true
	#If enabled, JourneyMap waypoints will only be created if the mod 'JourneyMap Integration' is not installed
	preferJourneyMapIntegrationMod = true
	#If enabled, Waystones will add markers for waystones and sharestones to BlueMap.
	blueMap = true
	#If enabled, Waystones will add markers for waystones and sharestones to Dynmap.
	dynmap = true
